name: Release - PR

on:
  workflow_dispatch:
# TODO: Uncomment the following lines to enable the workflow
#  push:
#    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: ZuCommunications/GH-shared/.github/workflows/php-release.yml@main
    secrets: inherit
    with:
      php-version: '8.2'
      package-files: 'config vendor web CHANGELOG.md composer.json package.json'
